### ISSUE TITLE
getchar definition wrong in UART example

### ISSUE THREAD

**Issue by ghost** [lujji/stm8-bare-min#2]
In the the trunk for SDCC, the definition for getchar returns an int
https://github.com/lujji/stm8-bare-min/blob/787c487f92a15fbd976b21e28b8576e0e08fe5f8/examples/UART/main.c#L19

**Comment by zoomx** [comment]
Are you sure? A char is only one byte.
`char getchar() {
    return uart_read();
}`

stm8/uart.c
`uint8_t uart_read() {
    while (!(UART1_SR & (1 << UART1_SR_RXNE)));
    return UART1_DR;
}`

**Comment by ghost** [comment]
Yes [here](https://github.com/svn2github/sdcc/blob/c71105d881e300711773366ca3ba01a21cd31e3a/sdcc/device/include/stdio.h) is the header file that shows this.

Its in the C99 standard, i'm not sure about before, and its been correct sdcc since [this](https://github.com/svn2github/sdcc/commit/10716af7c6f8442f41725c5620597995d6b7fab8#diff-b6ec86ca5bb7c47553536262e238f9e5) commit.

I'm not sure how to switch automatically depending upon which compiler version is being used. I'm more familiar with c++.

**Comment by zoomx** [comment]
I am not sure but I believe that the function getchar has only the same name of the one in stdio.h

**Comment by lujji** [comment]
fixed in https://github.com/lujji/stm8-bare-min/commit/2c2f9f731c120592a04cfd0e96f46fee466ca710
