### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by ebenolson** [lujji/stm8-bare-min#3]
Hi, is this code available under a particular license? Thanks!

**Comment by lujji** [comment]
I haven't thought about it, to be honest

**Comment by jabjoe** [comment]
Be nice it this was open to being used commercially. No license means default copyright, which is not a good license. For stuff like this highly permissive is good because it makes it an option for commercial use instead of the vendor stuff if you like libs and tools open and lightweight.

**Comment by johschmitz** [comment]
Some simple and permissive license such as BSD or MIT would be great. Just add the LICENSE file to the repo. Simplest way: go to Insights->Community->License->Add
